name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  base:
    strategy:
      fail-fast: false
      matrix:
        gem:
          - opentelemetry-api
          - opentelemetry-common
          - opentelemetry-metrics-api
          - opentelemetry-registry
          - opentelemetry-sdk
          - opentelemetry-semantic_conventions
          - opentelemetry-test-helpers
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: ${{ matrix.gem }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: "Test Ruby 3.1"
        uses: ./.github/actions/test_gem
        with:
          gem: "${{ matrix.gem }}"
          ruby: "3.1"
      - name: "Test Ruby 3.0"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "${{ matrix.gem }}"
          ruby: "3.0"
      - name: "Test Ruby 2.7"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "${{ matrix.gem }}"
          ruby: "2.7"
          yard: true
          rubocop: true
          build: true
      - name: "Test JRuby"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "${{ matrix.gem }}"
          ruby: "jruby"

  exporters:
    strategy:
      fail-fast: false
      matrix:
        gem:
          - opentelemetry-exporter-jaeger
          - opentelemetry-exporter-otlp
          - opentelemetry-exporter-zipkin
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        exclude:
          # Doesn't build on macos
          - os: macos-latest
            gem: opentelemetry-exporter-jaeger
    name: ${{ matrix.gem }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: "Test Ruby 3.1"
        uses: ./.github/actions/test_gem
        with:
          gem: "${{ matrix.gem }}"
          ruby: "3.1"
      - name: "Test Ruby 3.0"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "${{ matrix.gem }}"
          ruby: "3.0"
      - name: "Test Ruby 2.7"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "${{ matrix.gem }}"
          ruby: "2.7"
          yard: true
          rubocop: true
          build: true
      - name: "Test JRuby"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "${{ matrix.gem }}"
          ruby: "jruby"

  propagators:
    strategy:
      fail-fast: false
      matrix:
        gem:
          - opentelemetry-propagator-b3
          - opentelemetry-propagator-jaeger
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: ${{ matrix.gem }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: "Test Ruby 3.1"
        uses: ./.github/actions/test_gem
        with:
          gem: "${{ matrix.gem }}"
          ruby: "3.1"
      - name: "Test Ruby 3.0"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "${{ matrix.gem }}"
          ruby: "3.0"
      - name: "Test Ruby 2.7"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "${{ matrix.gem }}"
          ruby: "2.7"
          yard: true
          rubocop: true
          build: true
      - name: "Test JRuby"
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        uses: ./.github/actions/test_gem
        with:
          gem: "${{ matrix.gem }}"
          ruby: "jruby"
